[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chrono-kit"
version = "0.2.0"
authors = [
  { name="ODTU YZT", email="odtuyzt@gmail.com" },
]
description = "An open source python library for time series analysis and forecasting."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/odtuyzt/chrono-kit"